import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.scss'],
})
export class ProductsComponent implements OnInit {
  productList: any[] = [
    {
      id: 1,
      discount: '26%',
      price: '68,000 تومان',
      description: 'کوسن های نپالی',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '3.6',
    },
    {
      id: 2,
      discount: '15%',
      price: '167,000 تومان',
      description: 'قرمز سلطنتی',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '2.9',
    },
    {
      id: 3,
      discount: '23%',
      price: '98,000 تومان',
      description: 'ماندالا قاصدک',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '4.1',
    },
    {
      id: 4,
      discount: '18%',
      price: '150,000 تومان',
      description: 'کوسن های نپالی',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '4',
    },
    {
      id: 5,
      discount: '25%',
      price: '75,000 تومان',
      description: 'کوسن پروانه',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '4.5',
    },
    {
      id: 6,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '3',
    },
    {
      id: 7,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '3.9',
    },
    {
      id: 8,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '5',
    },
    {
      id: 9,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '4.8',
    },
    {
      id: 10,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '4.2',
    },
    {
      id: 11,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '2.9',
    },
    {
      id: 12,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '3.7',
    },
    {
      id: 13,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '4.1',
    },
    {
      id: 14,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '3.6',
    },
    {
      id: 15,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '4.9',
    },
    {
      id: 16,
      discount: '13%',
      price: '230,000 تومان',
      description: 'سرویس خواب دریم',
      image: '../../../assets/images/1.jpg',
      heart: '../../../assets/icons/heart2-svgrepo-com.svg',
      star: '../../../assets/icons/star-svgrepo-com.svg',
      rating: '4.9',
    },
  ];

  heartEl: any;
  redHeart(): any {
    this.heartEl = document.getElementById('heart-icon');
    this.heartEl.src = '../../../assets/icons/red-heart-svgrepo-com.svg';
  }
  constructor() {}

  ngOnInit(): void {}
}
